application: toluca-misterio
version: 1
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/blank/.*$
- ^/img-source/.*$

handlers:
- url: /css
  static_dir: static/css/
  secure: always
  login: required
- url: /js
  static_dir: static/js/
  secure: always
  login: required
- url: /fonts
  static_dir: static/fonts/
  secure: always
  login: required
- url: /lib
  static_dir: static/lib/
  secure: always
  login: required
- url: /partials
  static_dir: static/partials/
  secure: always
  login: required
- url: /img
  static_dir: static/img/
  secure: always
  login: required
  expiration: 1d
- url: /administration(/.*)?
  script: misterio.administration
  secure: always
  login: admin
- url: /.*
  script: misterio.application
  secure: always
  login: required
